# Generated by Django 5.2.4 on 2025-07-12 10:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
